export const jobs_title: string[] = ["3D Artist", "Account Executive", "Account Manager", "Accountant", "Actuary", "Aerospace Engineer", "Animator", "Assembler", "Attorney", "Auditor", "Automation Test Engineer", "Backend Developer", "Barista", "Bartender", "BI Analyst", "Biomedical Engineer", "Bookkeeper", "Brand Manager", "Business Analyst", "Carpenter", "Cashier", "Chef", "Chemical Engineer", "Civil Engineer", "Cloud Engineer", "Compensation & Benefits Analyst", "Compliance Counsel", "Compliance Officer", "Construction Manager", "Content Marketer", "Contract Manager", "Cook", "Credit Analyst", "Curriculum Developer", "Customer Success Manager", "Cybersecurity Analyst", "Data Analyst", "Data Engineer", "Data Privacy Officer", "Data Scientist", "Database Administrator", "Dentist", "DevOps Engineer", "Electrical Engineer", "Electrician", "Email Marketing Specialist", "Environmental Engineer", "E‑commerce Manager", "Financial Analyst", "Financial Manager", "Forklift Operator", "Frontend Developer", "Full‑Stack Developer", "Game Designer", "Game Developer", "Graphic Designer", "GRC Analyst", "Growth Manager", "Help Desk Technician", "HR Generalist", "HR Manager", "Incident Responder", "Industrial Engineer", "Information Security Manager", "Instructional Designer", "Investment Analyst", "IT Manager", "IT Support Specialist", "Legal Assistant", "Librarian", "Logistics Coordinator", "Machine Learning Engineer", "Marketing Manager", "Mechanical Engineer", "Medical Assistant", "Mobile Developer", "Motion Designer", "Network Engineer", "Nurse Practitioner", "Occupational Therapist", "Office Manager", "Operations Manager", "Paralegal", "Penetration Tester", "Performance Marketer", "Pharmacist", "Physical Therapist", "Physician", "Physician Assistant", "Plumber", "PPC Specialist", "PR Specialist", "Process Engineer", "Procurement Specialist", "Product Designer", "Product Manager", "Production Worker", "Professor", "Program Manager", "Project Manager", "QA Engineer", "Quality Engineer", "Radiologic Technologist", "Recruiter", "Registered Nurse", "Restaurant Manager", "Retail Sales Associate", "Risk Analyst", "Sales Manager", "Sales Representative", "Scrum Master", "Security Engineer", "SEO Specialist", "Site Reliability Engineer", "Social Media Manager", "Software Engineer", "Solutions Architect", "Sound Designer", "Store Manager", "Supply Chain Manager", "Systems Administrator", "Talent Acquisition Specialist", "Teacher", "Technical Writer", "Truck Driver", "UI Designer", "UX Designer", "Visual Merchandiser", "Warehouse Associate", "Welder"];

export const skills: string[] = [
    // Soft Skills
    "Accountability", "Active Listening", "Adaptability", "Analytical Skills", "Building Positive Relationships", "Clarity", "Collaboration", "Communication", "Conflict Mitigation", "Conflict Resolution", "Constructive Feedback", "Creativity", "Critical Reading", "Critical Thinking", "Cross-functional Collaboration", "Cultural Competence", "Curiosity", "Customer Service", "Data-Based Decision-Making", "Decision-Making", "Delegation", "Dependability", "Emotional Intelligence", "Empathy", "Etiquette", "Evidence-Based Reasoning", "Flexibility", "Goal Setting", "Identifying Patterns", "Identifying the Root Cause of the Problem", "Information Evaluation", "Innovative Thinking", "Interpersonal Skills", "Kindness", "Leadership", "Logical and Rational Thinking Processes", "Maturity", "Negotiation", "Nonverbal Communication", "Organizational Skills", "Planning", "Presentation Skills", "Prioritization", "Problem-Solving", "Public Speaking", "Punctuality", "Reasoning", "Reflection", "Resource Allocation", "Respectful Communication", "Self-Reflection", "Stakeholder Management", "Stress Management", "Team Management", "Teamwork", "Time Management", "Verbal Communication", "Written Communication",

    // Hard Skills
    "Action Planning", "Administrative Skills", "Budget and Resource Management", "Change Management", "Content Marketing", "Cost Management", "Customer Engagement and Support", "Data Analysis", "Data Interpretation", "Digital Marketing", "Email Marketing", "Financial Modeling", "Go-to-Market Strategy", "Growth Strategy", "Logistics and Coordination", "Marketing Strategy", "Process Optimization", "Project Budgeting", "Project Charters", "Project Closure and Evaluation", "Project Documentation", "Project Management", "Project Planning and Scheduling", "Recruitment and Talent Acquisition", "Regulatory Compliance", "Research", "Resource Allocation and Management", "Risk Identification and Mitigation", "Risk Management", "SEM (Search Engine Marketing)", "SEO (Search Engine Optimization)", "Social Media Marketing", "Solution-Based Selling", "Stakeholder Communication Plans",

    // Technical Skills
    "AI Literacy", "AngularJS", "API Development", "Artificial Intelligence", "AWS", "Azure", "C++", "Canva", "CI/CD", "Cloud Computing", "Couchbase", "Cybersecurity", "Data Visualization", "Databases", "DevOps", "Digital Collaboration Tools", "Docker", "ETL Tools", "Excel", "G-Suite", "Generative AI", "Google Cloud Platform", "GraphQL", "HTML/CSS", "HubSpot CRM", "Informatica", "Java", "JavaScript", "JSON Database Management", "JSON Schema Validation", "JSON Web Tokens (JWT)", "Kubernetes", "Large Language Model Development", "Machine Learning", "Microsoft Visio", "MongoDB", "MS Office", "Network Administration", "NoSQL", "Operating Systems", "PHP", "Power BI", "Programming Languages", "Python", "ReactJS", "Redis", "RESTful APIs", "Software Proficiency", "SQL", "Talend", "Typography and Layout Design", "UI Design", "UI/UX Design", "UX Wireframing", "Web Development"
].sort();